# -*- coding: utf-8 -*-
"""Matplotlib_Intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNHclvcS322Fppj4OPCKn5j9IX-j_rsA
"""

# Checking Matplotlib Version
import matplotlib
print(matplotlib.__version__)

"""Pyplot"""

# Draw a line in a diagram from position (0,0) to position (6,250)

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0,6])
y = np.array([0,300])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([1,5])
y = np.array([1,200])
plt.plot(x,y)
plt.show()